// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Interview Skills for Employment Success",
  "sourceHash": "69410ecb850b1919e3aedc0dc113e8d8efb82679a9c02f1010df95ec28ad21fd",
  "pictures": [
    {
      "slide": 1,
      "title": "Interview Skills for Employment Success",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 2,
      "title": "Warm-Up Activity",
      "label": "",
      "student": "print/s02.jpg",
      "teacher": "print/s02.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 3,
      "title": "Warm-Up: Sell an Object!",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 4,
      "title": "Understanding Interviews",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 5,
      "title": "What is an Interview?",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 6,
      "title": "Interviewing is a Skill",
      "label": "",
      "student": "print/s06.jpg",
      "teacher": "print/s06.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 7,
      "title": "The Interview Process",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 8,
      "title": "Every interview is a chance to grow. Practice builds confidence, and confidence gets the job.",
      "label": "",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 9,
      "title": "Preparing for the Interview",
      "label": "",
      "student": "print/s09.jpg",
      "teacher": "print/s09.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 10,
      "title": "Preparation Tips",
      "label": "",
      "student": "print/s10.jpg",
      "teacher": "print/s10.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 11,
      "title": "Researching the Employer",
      "label": "",
      "student": "print/s11.jpg",
      "teacher": "print/s11.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 12,
      "title": "Walk in prepared. Walk out confident.",
      "label": "",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Professional Presentation",
      "label": "",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 14,
      "title": "Dress for Success",
      "label": "",
      "student": "print/s14.jpg",
      "teacher": "print/s14.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 16,
      "title": "Body Language Matters",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 18,
      "title": "Body Language Tips",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Basic Interview Tips",
      "label": "",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Interview Techniques & Follow-Up",
      "label": "",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 21,
      "title": "The STAR Method",
      "label": "",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 22,
      "title": "STAR in Action: Handling Stress",
      "label": "",
      "student": "print/s22.jpg",
      "teacher": "print/s22.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 23,
      "title": "STAR in Action: Upset Customer",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 24,
      "title": "STAR Method Practice Activity",
      "label": "",
      "student": "print/s24.jpg",
      "teacher": "print/s24.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 25,
      "title": "Questions to Ask the Interviewer",
      "label": "",
      "student": "print/s25.jpg",
      "teacher": "print/s25.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 26,
      "title": "During & Closing the Interview",
      "label": "",
      "student": "print/s26.jpg",
      "teacher": "print/s26.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 27,
      "title": "Follow-Up Etiquette",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 28,
      "title": "ChatGPT Interview Practice",
      "label": "",
      "student": "print/s28.jpg",
      "teacher": "print/s28.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 29,
      "title": "Check Your Knowledge",
      "label": "",
      "student": "print/s29.jpg",
      "teacher": "print/s29.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "Interview Phase Review",
      "label": "tab 1 of 3",
      "student": "print/s30.jpg",
      "teacher": "print/s30.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "Interview Phase Review",
      "label": "tab 2 of 3",
      "student": "print/s30-v2.jpg",
      "teacher": "print/s30-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "Interview Phase Review",
      "label": "tab 3 of 3",
      "student": "print/s30-v3.jpg",
      "teacher": "print/s30-v3.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 31,
      "title": "STAR Method Practice: Think It Through",
      "label": "",
      "student": "print/s31.jpg",
      "teacher": "print/s31.jpg",
      "width": 2400,
      "height": 1419
    },
    {
      "slide": 32,
      "title": "Exit Ticket",
      "label": "",
      "student": "print/s32.jpg",
      "teacher": "print/s32-t.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Put It Into Practice",
      "label": "",
      "student": "print/s33.jpg",
      "teacher": "print/s33.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 34,
      "title": "Mock Interview Round Robin",
      "label": "",
      "student": "print/s34.jpg",
      "teacher": "print/s34.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 35,
      "title": "Final Thoughts",
      "label": "",
      "student": "print/s35.jpg",
      "teacher": "print/s35.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 36,
      "title": "Go get that job — you've got this!",
      "label": "",
      "student": "print/s36.jpg",
      "teacher": "print/s36.jpg",
      "width": 2400,
      "height": 1350
    }
  ]
};
