// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Time Management",
  "sourceHash": "17f56cae6e1785b602a32fa214a6d3233d4d8f173534a3ab79a37bf39ace773f",
  "pictures": [
    {
      "slide": 1,
      "title": "Time Management",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 2,
      "title": "Self-Reflection",
      "label": "",
      "student": "print/s02.jpg",
      "teacher": "print/s02.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 3,
      "title": "Module Objective",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 4,
      "title": "We All Have 24 Hours",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 5,
      "title": "Optimize Your Time",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 6,
      "title": "What You Will Be Able to Do",
      "label": "",
      "student": "print/s06.jpg",
      "teacher": "print/s06.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 7,
      "title": "Setting Priorities",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 8,
      "title": "What Are Priorities?",
      "label": "",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 10,
      "title": "The Big Rocks of Time",
      "label": "",
      "student": "print/s10.jpg",
      "teacher": "print/s10.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 11,
      "title": "You've identified your priorities...Now what?",
      "label": "",
      "student": "print/s11.jpg",
      "teacher": "print/s11.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 12,
      "title": "Tools & Strategies",
      "label": "",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Set SMART Goals",
      "label": "",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 14,
      "title": "Utilize a Flow Chart",
      "label": "",
      "student": "print/s14.jpg",
      "teacher": "print/s14.jpg",
      "width": 2400,
      "height": 1368
    },
    {
      "slide": 15,
      "title": "The Eisenhower Matrix",
      "label": "",
      "student": "print/s15.jpg",
      "teacher": "print/s15.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 16,
      "title": "Match the Task to the Action",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16-t.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "Daily & Weekly Planners",
      "label": "",
      "student": "print/s17.jpg",
      "teacher": "print/s17.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 18,
      "title": "Family To-Do Lists & Delegation",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Common Challenges",
      "label": "",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Time Management Dangers",
      "label": "card fronts",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Time Management Dangers",
      "label": "card backs",
      "student": "print/s20-v2.jpg",
      "teacher": "print/s20-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 21,
      "title": "Technology Distractions",
      "label": "",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 23,
      "title": "Procrastination",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 25,
      "title": "Multitasking",
      "label": "",
      "student": "print/s25.jpg",
      "teacher": "print/s25.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 27,
      "title": "Over-Commitment",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 28,
      "title": "Lack of Structure & Routine",
      "label": "",
      "student": "print/s28.jpg",
      "teacher": "print/s28.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "What Would You Do?",
      "label": "",
      "student": "print/s30.jpg",
      "teacher": "print/s30.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 31,
      "title": "Check Your Knowledge",
      "label": "",
      "student": "print/s31.jpg",
      "teacher": "print/s31.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 32,
      "title": "Quick Check",
      "label": "",
      "student": "print/s32.jpg",
      "teacher": "print/s32-t.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Assessment Debrief",
      "label": "",
      "student": "print/s33.jpg",
      "teacher": "print/s33.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 34,
      "title": "Exit Ticket",
      "label": "",
      "student": "print/s34.jpg",
      "teacher": "print/s34.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 35,
      "title": "Put It Into Practice",
      "label": "",
      "student": "print/s35.jpg",
      "teacher": "print/s35.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 36,
      "title": "How Will You Put Your TIME to Use?",
      "label": "",
      "student": "print/s36.jpg",
      "teacher": "print/s36.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 37,
      "title": "Own Your Time",
      "label": "",
      "student": "print/s37.jpg",
      "teacher": "print/s37.jpg",
      "width": 2400,
      "height": 1350
    }
  ]
};
