// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Communicating with the Public",
  "sourceHash": "de444474246cd5781f0303bdf86542fe5719630a9af156e6cae036571303784a",
  "pictures": [
    {
      "slide": 1,
      "title": "Communicating with the Public",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 2,
      "title": "Personal Listening Assessment",
      "label": "",
      "student": "print/s02.jpg",
      "teacher": "print/s02.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 3,
      "title": "Why Communication Matters",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 4,
      "title": "What is Communication?",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 5,
      "title": "Communication in the Workplace",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 7,
      "title": "Communication is not just about speaking — it's about being understood.",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 8,
      "title": "Elements of Communication",
      "label": "",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 9,
      "title": "Encoding & Decoding",
      "label": "",
      "student": "print/s09.jpg",
      "teacher": "print/s09.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 10,
      "title": "The Communication Cycle",
      "label": "",
      "student": "print/s10.jpg",
      "teacher": "print/s10.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 12,
      "title": "Hearing vs. Listening",
      "label": "",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Listening Skills",
      "label": "",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 15,
      "title": "Checkpoint",
      "label": "",
      "student": "print/s15.jpg",
      "teacher": "print/s15.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 16,
      "title": "Communication Styles",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "Three Communication Styles",
      "label": "tab 1 of 3",
      "student": "print/s17.jpg",
      "teacher": "print/s17.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "Three Communication Styles",
      "label": "tab 2 of 3",
      "student": "print/s17-v2.jpg",
      "teacher": "print/s17-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "Three Communication Styles",
      "label": "tab 3 of 3",
      "student": "print/s17-v3.jpg",
      "teacher": "print/s17-v3.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 18,
      "title": "Congruent Messages",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Watch: Bad Communication Examples",
      "label": "",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Practice: Role-Play Scenarios",
      "label": "",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 21,
      "title": "Self-Advocacy",
      "label": "",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 22,
      "title": "What is Self-Advocacy?",
      "label": "",
      "student": "print/s22.jpg",
      "teacher": "print/s22.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 23,
      "title": "Self-Advocacy in Action",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 24,
      "title": "Why Self-Advocacy Matters",
      "label": "",
      "student": "print/s24.jpg",
      "teacher": "print/s24.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 25,
      "title": "Building Self-Advocacy Skills",
      "label": "",
      "student": "print/s25.jpg",
      "teacher": "print/s25.jpg",
      "width": 2400,
      "height": 1488
    },
    {
      "slide": 26,
      "title": "Tips for Effective Self-Advocacy",
      "label": "",
      "student": "print/s26.jpg",
      "teacher": "print/s26.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 27,
      "title": "Self-Advocacy Resources",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 29,
      "title": "Reflect & Assess",
      "label": "",
      "student": "print/s29.jpg",
      "teacher": "print/s29.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "Personal Listening Assessment (Post)",
      "label": "",
      "student": "print/s30.jpg",
      "teacher": "print/s30.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 31,
      "title": "Apply Your Skills",
      "label": "",
      "student": "print/s31.jpg",
      "teacher": "print/s31.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 32,
      "title": "Self-Advocacy Binder Project",
      "label": "",
      "student": "print/s32.jpg",
      "teacher": "print/s32.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Communicate with Confidence",
      "label": "",
      "student": "print/s33.jpg",
      "teacher": "print/s33.jpg",
      "width": 2400,
      "height": 1350
    }
  ]
};
