// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Employee Accountability",
  "sourceHash": "6a0cb8091098a60418abf6cb17669d70126befc1ac62f336285568a29f8b41ce",
  "pictures": [
    {
      "slide": 1,
      "title": "Employee Accountability",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 2,
      "title": "Share Your Story",
      "label": "",
      "student": "print/s02.jpg",
      "teacher": "print/s02.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 3,
      "title": "Warm-Up: Share Your Story",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 4,
      "title": "What Is Employee Accountability?",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 5,
      "title": "Learning Objectives",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 6,
      "title": "Responsibility vs. Accountability",
      "label": "",
      "student": "print/s06.jpg",
      "teacher": "print/s06.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 7,
      "title": "What Is Employee Accountability?",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 8,
      "title": "Why Accountability Matters for Your Career",
      "label": "",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 9,
      "title": "Accountability is not about punishment —it is about ownership.",
      "label": "",
      "student": "print/s09.jpg",
      "teacher": "print/s09.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 10,
      "title": "Habits of Mind & Accountability",
      "label": "",
      "student": "print/s10.jpg",
      "teacher": "print/s10.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 11,
      "title": "What Are Habits of Mind?",
      "label": "",
      "student": "print/s11.jpg",
      "teacher": "print/s11.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 12,
      "title": "People who practice these habits don't blame others — they reflect, correct, and improve.",
      "label": "",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Key Habits of Mind for Accountability",
      "label": "",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 14,
      "title": "Self-Reflection: Where Do You Stand?",
      "label": "",
      "student": "print/s14.jpg",
      "teacher": "print/s14.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 15,
      "title": "Class Debrief: Habits of Mind",
      "label": "",
      "student": "print/s15.jpg",
      "teacher": "print/s15.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 16,
      "title": "Accountability & Team Success",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "How Accountability Strengthens Teams",
      "label": "card fronts",
      "student": "print/s17.jpg",
      "teacher": "print/s17.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 17,
      "title": "How Accountability Strengthens Teams",
      "label": "card backs",
      "student": "print/s17-v2.jpg",
      "teacher": "print/s17-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 18,
      "title": "The 5 Cs of Accountability",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Explore the 5 Cs — Deeper Dive",
      "label": "tab 1 of 5",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Explore the 5 Cs — Deeper Dive",
      "label": "tab 2 of 5",
      "student": "print/s19-v2.jpg",
      "teacher": "print/s19-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Explore the 5 Cs — Deeper Dive",
      "label": "tab 3 of 5",
      "student": "print/s19-v3.jpg",
      "teacher": "print/s19-v3.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Explore the 5 Cs — Deeper Dive",
      "label": "tab 4 of 5",
      "student": "print/s19-v4.jpg",
      "teacher": "print/s19-v4.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Explore the 5 Cs — Deeper Dive",
      "label": "tab 5 of 5",
      "student": "print/s19-v5.jpg",
      "teacher": "print/s19-v5.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Accountability and Personal Growth",
      "label": "",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 21,
      "title": "The 5 Cs are not rules someone gives you —they are commitments you make to yourself.",
      "label": "",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 22,
      "title": "Principles, Mindset & Workplace Application",
      "label": "",
      "student": "print/s22.jpg",
      "teacher": "print/s22.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 23,
      "title": "6 Powerful Principles of Personal Accountability",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1731
    },
    {
      "slide": 24,
      "title": "Victim Road vs. Accountable Road",
      "label": "",
      "student": "print/s24.jpg",
      "teacher": "print/s24.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 25,
      "title": "The question is not \"How do I avoid it?\" It is \"How fast can I get through it?\"",
      "label": "",
      "student": "print/s25.jpg",
      "teacher": "print/s25.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 26,
      "title": "Three Areas of Personal Accountability",
      "label": "",
      "student": "print/s26.jpg",
      "teacher": "print/s26.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 27,
      "title": "Workplace Scenario: Checkpoint",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27-t.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 28,
      "title": "SMART Goals & Assessment",
      "label": "",
      "student": "print/s28.jpg",
      "teacher": "print/s28.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 29,
      "title": "SMART Goals: Turning Accountability Into Action",
      "label": "",
      "student": "print/s29.jpg",
      "teacher": "print/s29.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 30,
      "title": "Write Your SMART Goal",
      "label": "",
      "student": "print/s30.jpg",
      "teacher": "print/s30.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 31,
      "title": "Apply It & Commit",
      "label": "",
      "student": "print/s31.jpg",
      "teacher": "print/s31.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 32,
      "title": "Career Planning: Your Accountability in Action",
      "label": "",
      "student": "print/s32.jpg",
      "teacher": "print/s32.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Round Robin: Commit Out Loud",
      "label": "card 1 of 3",
      "student": "print/s33.jpg",
      "teacher": "print/s33.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Round Robin: Commit Out Loud",
      "label": "card 2 of 3",
      "student": "print/s33-v2.jpg",
      "teacher": "print/s33-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Round Robin: Commit Out Loud",
      "label": "card 3 of 3",
      "student": "print/s33-v3.jpg",
      "teacher": "print/s33-v3.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 34,
      "title": "Key Takeaways",
      "label": "",
      "student": "print/s34.jpg",
      "teacher": "print/s34.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 35,
      "title": "Own It. Grow From It. Lead With It.",
      "label": "",
      "student": "print/s35.jpg",
      "teacher": "print/s35.jpg",
      "width": 2400,
      "height": 1350
    }
  ]
};
