// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Controlling Anger",
  "sourceHash": "1d22e9c1601e46b74257eb53d6119cca3e8e1e441bf2fee89a7dd453da7932e5",
  "pictures": [
    {
      "slide": 1,
      "title": "Controlling Anger",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 3,
      "title": "What Makes Us Angry?",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 4,
      "title": "Healthy vs. Unhealthy Anger",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 5,
      "title": "The Two Sides of Anger",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 6,
      "title": "What Is Healthy Anger?",
      "label": "",
      "student": "print/s06.jpg",
      "teacher": "print/s06.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 7,
      "title": "Anger is not the problem. How we handle it is.",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 8,
      "title": "The Anger Iceberg",
      "label": "",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 9,
      "title": "Below the Surface of Anger",
      "label": "",
      "student": "print/s09.jpg",
      "teacher": "print/s09.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 11,
      "title": "Reflect: What’s Beneath Your Anger?",
      "label": "",
      "student": "print/s11.jpg",
      "teacher": "print/s11.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 12,
      "title": "Building Better Support Networks",
      "label": "",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Anger at Work & in Interviews",
      "label": "card fronts",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 13,
      "title": "Anger at Work & in Interviews",
      "label": "card backs",
      "student": "print/s13-v2.jpg",
      "teacher": "print/s13-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 14,
      "title": "Strategies for Managing Anger",
      "label": "",
      "student": "print/s14.jpg",
      "teacher": "print/s14.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 15,
      "title": "Embrace, Express & Work Through",
      "label": "tab 1 of 3",
      "student": "print/s15.jpg",
      "teacher": "print/s15.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 15,
      "title": "Embrace, Express & Work Through",
      "label": "tab 2 of 3",
      "student": "print/s15-v2.jpg",
      "teacher": "print/s15-v2.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 15,
      "title": "Embrace, Express & Work Through",
      "label": "tab 3 of 3",
      "student": "print/s15-v3.jpg",
      "teacher": "print/s15-v3.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 16,
      "title": "Recognize Your Triggers",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 18,
      "title": "Debrief: Your Warning Signs",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 19,
      "title": "Fair Fighting: Rules 1–5",
      "label": "",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 20,
      "title": "Fair Fighting: Rules 6–10",
      "label": "",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 21,
      "title": "Hands-On Activities",
      "label": "",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 22,
      "title": "Pair & Share: Speak and Listen",
      "label": "",
      "student": "print/s22.jpg",
      "teacher": "print/s22.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 23,
      "title": "Controlling Anger Choice Wheel",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 24,
      "title": "12 Ways to Manage Anger",
      "label": "",
      "student": "print/s24.jpg",
      "teacher": "print/s24.jpg",
      "width": 2400,
      "height": 1502
    },
    {
      "slide": 26,
      "title": "Drinking Poison: The Cost of Holding On",
      "label": "",
      "student": "print/s26.jpg",
      "teacher": "print/s26.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 27,
      "title": "Review & Assess",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 28,
      "title": "Jeopardy Review Game",
      "label": "",
      "student": "print/s28.jpg",
      "teacher": "print/s28.jpg",
      "width": 2400,
      "height": 1399
    },
    {
      "slide": 29,
      "title": "Check Your Understanding",
      "label": "",
      "student": "print/s29.jpg",
      "teacher": "print/s29-t.jpg",
      "width": 2400,
      "height": 1434
    },
    {
      "slide": 30,
      "title": "Reflect & Apply",
      "label": "",
      "student": "print/s30.jpg",
      "teacher": "print/s30.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 31,
      "title": "Styles of Anger Assessment",
      "label": "",
      "student": "print/s31.jpg",
      "teacher": "print/s31.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 32,
      "title": "Final Reflection",
      "label": "",
      "student": "print/s32.jpg",
      "teacher": "print/s32.jpg",
      "width": 2400,
      "height": 1350
    },
    {
      "slide": 33,
      "title": "Congratulations, you have completed this lesson!",
      "label": "",
      "student": "print/s33.jpg",
      "teacher": "print/s33.jpg",
      "width": 2400,
      "height": 1350
    }
  ]
};
