// Generated by scripts/capture-print-slides.mjs. Do not edit by hand.
window.SPOKES_PRINT_MANIFEST = {
  "version": 1,
  "lessonTitle": "Problem-Solving & Decision-Making",
  "sourceHash": "01d787b68602696999269952c93d301fe1a68ec3e2ded87c7104fe108ee142a7",
  "pictures": [
    {
      "slide": 1,
      "title": "Problem-Solving & Decision-Making",
      "label": "",
      "student": "print/s01.jpg",
      "teacher": "print/s01.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 3,
      "title": "Critical Thinking Quiz",
      "label": "",
      "student": "print/s03.jpg",
      "teacher": "print/s03-t.jpg",
      "width": 2400,
      "height": 2125
    },
    {
      "slide": 4,
      "title": "Objectives",
      "label": "",
      "student": "print/s04.jpg",
      "teacher": "print/s04.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 5,
      "title": "Critical Thinking in Action",
      "label": "",
      "student": "print/s05.jpg",
      "teacher": "print/s05.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 7,
      "title": "Problem-Solving Styles",
      "label": "",
      "student": "print/s07.jpg",
      "teacher": "print/s07.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 8,
      "title": "The Four Styles",
      "label": "card fronts",
      "student": "print/s08.jpg",
      "teacher": "print/s08.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 8,
      "title": "The Four Styles",
      "label": "card backs",
      "student": "print/s08-v2.jpg",
      "teacher": "print/s08-v2.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 9,
      "title": "The Four-Step Process",
      "label": "",
      "student": "print/s09.jpg",
      "teacher": "print/s09.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 11,
      "title": "Four Steps to Better Decisions",
      "label": "",
      "student": "print/s11.jpg",
      "teacher": "print/s11.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 12,
      "title": "The Four Steps in Detail",
      "label": "tab 1 of 4",
      "student": "print/s12.jpg",
      "teacher": "print/s12.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 12,
      "title": "The Four Steps in Detail",
      "label": "tab 2 of 4",
      "student": "print/s12-v2.jpg",
      "teacher": "print/s12-v2.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 12,
      "title": "The Four Steps in Detail",
      "label": "tab 3 of 4",
      "student": "print/s12-v3.jpg",
      "teacher": "print/s12-v3.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 12,
      "title": "The Four Steps in Detail",
      "label": "tab 4 of 4",
      "student": "print/s12-v4.jpg",
      "teacher": "print/s12-v4.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 13,
      "title": "Let’s Try It Together",
      "label": "",
      "student": "print/s13.jpg",
      "teacher": "print/s13.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 14,
      "title": "Group Scenarios",
      "label": "",
      "student": "print/s14.jpg",
      "teacher": "print/s14.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 16,
      "title": "Group Scenario Activity",
      "label": "",
      "student": "print/s16.jpg",
      "teacher": "print/s16.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 17,
      "title": "Choose a Scenario",
      "label": "",
      "student": "print/s17.jpg",
      "teacher": "print/s17.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 18,
      "title": "Survival Challenge",
      "label": "",
      "student": "print/s18.jpg",
      "teacher": "print/s18.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 19,
      "title": "Survival Activity",
      "label": "",
      "student": "print/s19.jpg",
      "teacher": "print/s19.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 20,
      "title": "Lost at Sea — Expert Rankings",
      "label": "tab 1 of 2",
      "student": "print/s20.jpg",
      "teacher": "print/s20.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 20,
      "title": "Lost at Sea — Expert Rankings",
      "label": "tab 2 of 2",
      "student": null,
      "teacher": "print/s20-v2-t.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 21,
      "title": "Lunar Survival — NASA Rankings",
      "label": "tab 1 of 2",
      "student": "print/s21.jpg",
      "teacher": "print/s21.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 21,
      "title": "Lunar Survival — NASA Rankings",
      "label": "tab 2 of 2",
      "student": null,
      "teacher": "print/s21-v2-t.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 22,
      "title": "Every problem is a chance to think differently.",
      "label": "",
      "student": "print/s22.jpg",
      "teacher": "print/s22.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 23,
      "title": "3–2–1 Reflection",
      "label": "",
      "student": "print/s23.jpg",
      "teacher": "print/s23.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 24,
      "title": "3 – 2 – 1 Reflection",
      "label": "",
      "student": "print/s24.jpg",
      "teacher": "print/s24.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 25,
      "title": "Share & Apply",
      "label": "",
      "student": "print/s25.jpg",
      "teacher": "print/s25.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 26,
      "title": "Key Takeaways",
      "label": "",
      "student": "print/s26.jpg",
      "teacher": "print/s26.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 27,
      "title": "Share Your Reflections",
      "label": "",
      "student": "print/s27.jpg",
      "teacher": "print/s27.jpg",
      "width": 2400,
      "height": 1352
    },
    {
      "slide": 28,
      "title": "Think. Decide. Act.",
      "label": "",
      "student": "print/s28.jpg",
      "teacher": "print/s28.jpg",
      "width": 2400,
      "height": 1352
    }
  ]
};
